/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Formularios.admin;

import Clases.usuarios;
import clasesDAO.usuarios_DAO;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author david
 */
public class asignarPuestos extends javax.swing.JInternalFrame {
    usuarios_DAO user;
    ArrayList<usuarios> listausuarios;
    DefaultTableModel model1;
    public asignarPuestos() {
        initComponents();
         model1 = (DefaultTableModel) jTable1.getModel();
         this.cargar();
    }
    public void cargar(){
        user= new usuarios_DAO();
        listausuarios= user.obtenerTodosLosUsuarios();
        model1.setRowCount(0);
        for (usuarios usuario : listausuarios) {
        model1.addRow(new Object[]{
            usuario.getIdUsuario(),
            usuario.getNombre(),
            usuario.getApellido(),
            usuario.getInicio() // fecha de contratación
        });
    }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        main = new javax.swing.JPanel();
        header = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cbxPuesto = new javax.swing.JComboBox<>();
        btnSalirEmpleado = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnGuardarEmpleado1 = new javax.swing.JButton();
        btnGuardarEmpleado2 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setBorder(null);

        main.setBackground(new java.awt.Color(255, 255, 255));
        main.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        header.setBackground(new java.awt.Color(102, 153, 255));

        jLabel2.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        jLabel2.setText("Asignar Puestos");

        javax.swing.GroupLayout headerLayout = new javax.swing.GroupLayout(header);
        header.setLayout(headerLayout);
        headerLayout.setHorizontalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 690, Short.MAX_VALUE)
            .addGroup(headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(headerLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel2)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        headerLayout.setVerticalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 64, Short.MAX_VALUE)
            .addGroup(headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(headerLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel2)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        main.add(header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 690, -1));

        jLabel3.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel3.setText("PUESTO");
        main.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 530, -1, -1));

        cbxPuesto.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        cbxPuesto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Chef", "Bodeguero", "Cocinero", "Bar tender", "Recepcionista" }));
        main.add(cbxPuesto, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 520, 170, 30));

        btnSalirEmpleado.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        btnSalirEmpleado.setText("SALIR");
        btnSalirEmpleado.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 153)));
        btnSalirEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirEmpleadoActionPerformed(evt);
            }
        });
        main.add(btnSalirEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 530, 90, 30));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Número de empleado", "Nombre", "Apellido", "Fecha Contratacion"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable1);

        main.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 690, 190));

        btnGuardarEmpleado1.setBackground(new java.awt.Color(0, 102, 153));
        btnGuardarEmpleado1.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        btnGuardarEmpleado1.setForeground(new java.awt.Color(255, 255, 255));
        btnGuardarEmpleado1.setText("Editar");
        main.add(btnGuardarEmpleado1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 530, -1, 30));

        btnGuardarEmpleado2.setBackground(new java.awt.Color(0, 102, 153));
        btnGuardarEmpleado2.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        btnGuardarEmpleado2.setForeground(new java.awt.Color(255, 255, 255));
        btnGuardarEmpleado2.setText("GUARDAR");
        main.add(btnGuardarEmpleado2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 530, -1, 30));

        jTextField1.setText("Buscar");
        main.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 650, -1));

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setText("Informacion del Salario de Acuerdo al puesto\n\n1- Chef $3200.59\n");
        jScrollPane1.setViewportView(jTextArea1);

        main.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, 220, 170));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(main, javax.swing.GroupLayout.DEFAULT_SIZE, 722, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(main, javax.swing.GroupLayout.DEFAULT_SIZE, 570, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirEmpleadoActionPerformed
        Principal us= new Principal();
        us.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnSalirEmpleadoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardarEmpleado1;
    private javax.swing.JButton btnGuardarEmpleado2;
    private javax.swing.JButton btnSalirEmpleado;
    private javax.swing.JComboBox<String> cbxPuesto;
    private javax.swing.JPanel header;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JPanel main;
    // End of variables declaration//GEN-END:variables
}
