/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Formularios.admin;

/**
 *
 * @author david
 */
public class inventarios_admin extends javax.swing.JInternalFrame {

    /**
     * Creates new form inventario_admin
     */
    public inventarios_admin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        main = new javax.swing.JPanel();
        header = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        panel_ingredientes = new javax.swing.JPanel();
        txtBuscarIngredientes = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblIngredientes = new javax.swing.JTable();
        btnAggIngrediente = new javax.swing.JButton();
        btnEditarIngrediente = new javax.swing.JButton();
        btnEliminarIngrediente = new javax.swing.JButton();
        panel_utensilios = new javax.swing.JPanel();
        txtBuscarUtensilios = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblUtensilios = new javax.swing.JTable();
        btnAggUtensilio = new javax.swing.JButton();
        btnEditarUtensilio = new javax.swing.JButton();
        btnEliminarUtensilio = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setBorder(null);

        main.setBackground(new java.awt.Color(255, 255, 255));
        main.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        header.setBackground(new java.awt.Color(102, 153, 255));

        jLabel2.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        jLabel2.setText("INVENTARIOS");

        javax.swing.GroupLayout headerLayout = new javax.swing.GroupLayout(header);
        header.setLayout(headerLayout);
        headerLayout.setHorizontalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
            .addGroup(headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(headerLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel2)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        headerLayout.setVerticalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
            .addGroup(headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(headerLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel2)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        main.add(header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, -1));

        jTabbedPane1.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N

        panel_ingredientes.setBackground(new java.awt.Color(255, 255, 255));

        txtBuscarIngredientes.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        txtBuscarIngredientes.setForeground(new java.awt.Color(204, 204, 204));
        txtBuscarIngredientes.setText("Buscar ingredientes");

        tblIngredientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Nombre", "Cantidad", "Estado", "Fecha Ingreso", "Vencimiento"
            }
        ));
        jScrollPane1.setViewportView(tblIngredientes);

        btnAggIngrediente.setBackground(new java.awt.Color(0, 102, 153));
        btnAggIngrediente.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        btnAggIngrediente.setForeground(new java.awt.Color(255, 255, 255));
        btnAggIngrediente.setText("Agregar ");

        btnEditarIngrediente.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        btnEditarIngrediente.setText("Editar");
        btnEditarIngrediente.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 153)));

        btnEliminarIngrediente.setBackground(new java.awt.Color(0, 102, 153));
        btnEliminarIngrediente.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        btnEliminarIngrediente.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminarIngrediente.setText("Eliminar");

        javax.swing.GroupLayout panel_ingredientesLayout = new javax.swing.GroupLayout(panel_ingredientes);
        panel_ingredientes.setLayout(panel_ingredientesLayout);
        panel_ingredientesLayout.setHorizontalGroup(
            panel_ingredientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_ingredientesLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(panel_ingredientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panel_ingredientesLayout.createSequentialGroup()
                        .addComponent(btnAggIngrediente)
                        .addGap(10, 10, 10)
                        .addComponent(btnEditarIngrediente, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(btnEliminarIngrediente))
                    .addComponent(txtBuscarIngredientes)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 752, Short.MAX_VALUE))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        panel_ingredientesLayout.setVerticalGroup(
            panel_ingredientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_ingredientesLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(txtBuscarIngredientes, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panel_ingredientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAggIngrediente, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEditarIngrediente, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEliminarIngrediente, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("INGREDIENTES", panel_ingredientes);

        panel_utensilios.setBackground(new java.awt.Color(255, 255, 255));

        txtBuscarUtensilios.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        txtBuscarUtensilios.setForeground(new java.awt.Color(204, 204, 204));
        txtBuscarUtensilios.setText("Buscar utensilios");

        tblUtensilios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nombre", "Cantidad", "Estado", "Fecha Ingreso"
            }
        ));
        jScrollPane2.setViewportView(tblUtensilios);

        btnAggUtensilio.setBackground(new java.awt.Color(0, 102, 153));
        btnAggUtensilio.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        btnAggUtensilio.setForeground(new java.awt.Color(255, 255, 255));
        btnAggUtensilio.setText("Agregar ");

        btnEditarUtensilio.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        btnEditarUtensilio.setText("Editar");
        btnEditarUtensilio.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 153)));

        btnEliminarUtensilio.setBackground(new java.awt.Color(0, 102, 153));
        btnEliminarUtensilio.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        btnEliminarUtensilio.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminarUtensilio.setText("Eliminar");

        javax.swing.GroupLayout panel_utensiliosLayout = new javax.swing.GroupLayout(panel_utensilios);
        panel_utensilios.setLayout(panel_utensiliosLayout);
        panel_utensiliosLayout.setHorizontalGroup(
            panel_utensiliosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_utensiliosLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(panel_utensiliosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panel_utensiliosLayout.createSequentialGroup()
                        .addComponent(btnAggUtensilio)
                        .addGap(10, 10, 10)
                        .addComponent(btnEditarUtensilio, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(btnEliminarUtensilio))
                    .addComponent(txtBuscarUtensilios)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 755, Short.MAX_VALUE))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        panel_utensiliosLayout.setVerticalGroup(
            panel_utensiliosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_utensiliosLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(txtBuscarUtensilios, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panel_utensiliosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAggUtensilio, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEditarUtensilio, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEliminarUtensilio, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("UTENSILIOS", panel_utensilios);

        main.add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 800, 370));

        jButton1.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jButton1.setText("REGRESAR");
        jButton1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 255)));
        main.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 480, 120, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(main, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(main, javax.swing.GroupLayout.PREFERRED_SIZE, 538, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAggIngrediente;
    private javax.swing.JButton btnAggUtensilio;
    private javax.swing.JButton btnEditarIngrediente;
    private javax.swing.JButton btnEditarUtensilio;
    private javax.swing.JButton btnEliminarIngrediente;
    private javax.swing.JButton btnEliminarUtensilio;
    private javax.swing.JPanel header;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JPanel main;
    private javax.swing.JPanel panel_ingredientes;
    private javax.swing.JPanel panel_utensilios;
    private javax.swing.JTable tblIngredientes;
    private javax.swing.JTable tblUtensilios;
    private javax.swing.JTextField txtBuscarIngredientes;
    private javax.swing.JTextField txtBuscarUtensilios;
    // End of variables declaration//GEN-END:variables
}
